title: Signal Vizualizers
description:  >- # ignore new lines
  Animated visualizers for signal processing.
  <br><br>
  Simulations for the animations are
  created with
  <a href="https://neurodsp-tools.github.io/">NeuroDSP</a>.
  <br><br>
  Animations are available for re-use under the
  <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a>.
  <br><br>
  Developed by <br>
  <a href="https://tomdonoghue.github.io/">Tom Donoghue</a>.

show_downloads: false
#google_analytics: XX

twitter_username: TomDonoghue
github_username: TomDonoghue

theme: jekyll-theme-dinky