title: SigViz

description:  >- # ignore new lines
  Tutorials & visualizers for signal processing.
  <br><br>
  <a href="https://timeserieszoo.github.io/">Home</a>
  <br>
  Signals
  <br>
  <a href="https://timeserieszoo.github.io/signals/time_domain">Time Domain</a>
  <br>
  *Transforms*
  <br>
  <a href="https://timeserieszoo.github.io/transforms/fourier">Fourier</a>
  <br>
  <a href="https://timeserieszoo.github.io/transforms/convolution">Convolution</a>
  <br>
  <a href="https://timeserieszoo.github.io/transforms/filters">Filters</a>
  <br>
  __Tutorial__
  <br>
  <a href="https://timeserieszoo.github.io/tutorial/01_overview">1) Overview</a>
  <br>
  <a href="https://timeserieszoo.github.io/tutorial/02_sigs">2) Processing</a>
  <br>
  <a href="https://timeserieszoo.github.io/tutorial/03_ephys">3) Electrophysiology</a>
  <br>
  <a href="https://timeserieszoo.github.io/tutorial/04_specparam">4) Spectral Parameterization</a>
  <br><br>

show_downloads: false

github_username: TomDonoghue

theme: jekyll-theme-dinky
