title: Signal Vizualizers
description:  >- # ignore new lines
  Animated visualizers for signal processing.
  <br><br>
  Pages
  <br>
  <a href="https://timeserieszoo.github.io/">Home</a>
  <br>
  <a href="https://timeserieszoo.github.io/signals">Signals</a>
  <br>
  <a href="https://timeserieszoo.github.io/fourier">Fourier</a>
  <br>
  <a href="https://timeserieszoo.github.io/convolution">Convolution</a>
  <br>
  <a href="https://timeserieszoo.github.io/filters">Filters</a>
  <br><br>
  Developed by <br>
  <a href="https://tomdonoghue.github.io/">Tom Donoghue</a>.

show_downloads: false

github_username: TomDonoghue

theme: jekyll-theme-dinky